### ISSUE TITLE
SDL "Waiting for connection" notification not disappearing while connected to non SDL BT devices

### ISSUE THREAD

**Issue by SilvioDC-Ford** [smartdevicelink/sdl_java_suite#1619]
### Bug Report
We observed the SDL "Waiting for connection" notification in some cases  to not disappear when connecting to BT devices which are not SDL capable.
So far we could only see this on Samsung devices.
[PowerApp](https://play.google.com/store/apps/details?id=com.vakko.power&hl=de&gl=US) customers also see this issue and started complaining.

In most of the connections it works fine, so for reproduction one needs to either connect very often to the device (~1 issue per 15 connections) or stay connected for very long (>1h)

It seems like all of the cases where we saw the issue where in connection with more sophisticated BT devices, which have companion apps

##### Reproduction Steps
1. Open PowerApp or any other App with SDL lib > 4.11.1
2. Turn on BT and connect to a non sdl device
3. Wait

In most of the connections it works fine, so for reproduction one needs to either connect very often to the device (~1 issue per 15 connections) or stay connected for very long (>1h)

##### Expected Behavior
The Notification should disapear very quickly

##### Observed Behavior
From time to time the noticication stays forever

##### OS & Version Information
* Android Version: 10/11
* SDL Android Version: 4.11.1/4.12.0/4.12.2/5.0.0

We saw this issue on:
Samsung S8/S9/S10/A5/Note20 in combination with: Samsung watch S3, Oppo watch, Sony headset
We did not see it on pixel phones.
Our test app was build as debug type to gather more logs, while powerapp is build as release type. 
@mjuarez-ford took the below logs

##### Test Case, Sample Code, and / or Example App
![test app issue](https://user-images.githubusercontent.com/42735200/108385383-e6f5b080-720b-11eb-8e3c-4bb96252acf3.jpg)
![power app issue](https://user-images.githubusercontent.com/42735200/108385413-eeb55500-720b-11eb-8caa-e661241d8384.jpg)
[logfile](https://github.com/smartdevicelink/sdl_java_suite/files/6004190/4_12_2_samsung.log)
(It showed up around 00:00:40)

**Comment by joeygrover** [comment]
1. Can you confirm with **only** your dev app installed that the issue occurs with SDL library version 5.0.0 or 4.12.+? This should have mostly been resolved in 4.12.0 as the router service shouldn't start unless an SDL connection is made first in the broadcast receiver. It is likely that the older app integration in PowerApp is causing the router service to start since it does not perform this check first.
2. PowerApp is not a certified application, but as it seems is in production; this is an issue. No Android SDL application should be in production without being certified. If they are not approved through the SDLC then no other app will trust their router service and it will cause connectivity issues. Therefore the integration done by the app developers can't be confirmed as correct.
3. I would advise PowerApp to update their library to at least 4.12.2 to incorporate the fix to the notification issue and submit their application for certification.

**Comment by SilvioDC-Ford** [comment]
Thanks for the super quick response @joeygrover !

1) @mjuarez-ford will try reproducing it with only the dev app as single sdl app on the phone.
2+3)I reminded them to go through the certification steps (the sdl certification tests were passed before the app went to production). They are already using sdl library 5.0.0

**Comment by joeygrover** [comment]
Not a problem. This issue is the biggest thorn in the side of this project so I want to try and address as soon as possible.

1\. I notice in the logs that at least 3 apps installed and one of which is another non certified app, but I know is going through the process. I think it's key to try with only the single debug app.

2\3\. Understood. If they past their self certification it should be a relatively quick turn around to get officially certified. It is important that developers go through the process. I assumed they were on 4.11 based on the issue description, but if they are on 5.0.0 then there might be a different partner that is on a lower version. 

4\. For reference there have been several issues related to this behavior that we have addressed over the past that might be worth looking through. The most likely culprit is related to the issue #1351 . Samsung devices don't properly delete/handle the notifications and would cause a fatal crash, so the delete had to be skipped on those devices. To avoid getting in this situation, the subsequent release contained the feature to not even start the router service unless an SDL connection was made in the broadcast receiver during that connection or a previous one via caching the results.

I know we have a few of the Samsung devices but definitely not the other BT accessories so it might be hard for us to replicate if this issue truly still exists.

**Comment by mjuarez-ford** [comment]
Hello @joeygrover please find attached the logs only with the test app. Device to test was a Samsung S7 edge. Android 8.0
[sample_sdl.log](https://github.com/smartdevicelink/sdl_java_suite/files/6023457/sample_sdl.log)

**Comment by joeygrover** [comment]
> Hello @joeygrover please find attached the logs only with the test app. Device to test was a Samsung S7 edge. Android 8.0
> [sample_sdl.log](https://github.com/smartdevicelink/sdl_java_suite/files/6023457/sample_sdl.log)

```
02-22 12:51:29.643  4923  5841 I ActivityManager: Start proc 29396:com.cisco.webex.meetings/u0a386 for broadcast com.cisco.webex.meetings/.SdlReceiver
02-22 12:51:33.225  4923 11795 I ActivityManager: Start proc 29477:com.smartdevicelink.router/u0a421 for service com.example.samplesdlapp/.SdlRouterService
```
It seems there are two SDL apps still installed. I see that helloSdl was also installed at one point. If you can clear out all other apps prior to logging that might be helpful. Also make sure debug logging is enabled on the SDL library.

**Comment by joeygrover** [comment]
Hi @mjuarez-ford were you able to test with only the sample application or are there any additional updates?

**Comment by SilvioDC-Ford** [comment]
I try to summarize @mjuarez-fords findings, please correct me if something is wrong.

With only the sample app installed - the issue was not reproducible.
With two sample apps (both on 5.0.0 with different app name/ID) - the issue was still not reproducible.

When other apps, like in the above case Webex, with an older proxy version are present, the issue shows up.

So probably the old versions are still the root cause for the issue, but it still often shows as if the issue lies in the apps which have the most recent library. 
We now have two partners on 5.0.0 who see this issue.

We always try to motivate our partners to update to the most recent library, but there will always be some with older versions.
Any idea how this could be fixed, that not the diligent partners with the newest version get complaints from their customers?

**Comment by joeygrover** [comment]
Closing this issue as it is not a bug. It appears things are working as expected so this issue will no longer be open but discussion can continue here.

I would recommend reading through the proposal for the new feature that handles this. It provides some motivation and also includes the potential downside related to apps not updating. https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0301-SDL-device-listener.md

I have discussed this topic many times through many different forums to explain so it might be helpful to also retrieve minutes from older SDLC Steering Committee meetings. For future reference I will give a recap here and I apologize for the length:

#### Background 

First, the biggest issue we have is that when a bluetooth device connects to the mobile phone through the media and phone profiles we only have the MAC address and sometimes the friendly name. Because of how SDL (or AppLink) at the time was setup, the app library has to act as the server side of the SPP connection. This means we can't do an SDP query on the BT device to know if it supports SDL or not, and therefore, the library is burdened with a "Wait and see" approach. It opens the SPP connection and waits for the bluetooth device to connect to it. This is the only way to truly know if a BT device supports SDL or not, a successful SPP connection.

While we do know the MAC address and sometimes friendly name, it is not a scalable feature to keep a list of all supported devices at all times. The list itself would be very large as well as consistently being updated. It also is not the best at deterring if SDL is enabled because a friendly name could be reused between different lines of IVI systems within the same model of vehicle.


#### How the library handles this

Previously this was not a huge issue because we could start the router service in the background. However, since services had to be taken to the foreground we've entered into our biggest pain point with the Android OS. The feature itself on Android is extremely flawed and creates a lot of corner cases that we have to address. One of these issues is that a service started in the foreground must enter the foreground within a certain time limit, however that time limit starts when the caller requests the service to start, not when the actual service starts. This puts our service at the mercy of the OS system and hoping that there is enough time to enter the foreground once actually started. It has been seen that the OS throws an exception before the service is even started because that service didn't enter the foreground in time.

The library also implemented the ability to cache known MAC addresses for successful connections so it knew how long to wait in the foreground and prevent the notification from displaying on non SDL devices. This was creating a dynamic list that was specific to each phone/app.

The next and biggest issue is that the notification system is implemented differently between OS versions, manufactures, and even models. This means that on some devices things work as expected, some don't clear the notification even when the service exits the foreground, stops, and deletes the channel, or does not honor the API calls as they should be. This last case is what we see with Samsung devices. While we delete the channel and the notification clears, the next attempt to create the notification fails and causes a crash because the channel can't be found nor can it be recreated. This is why the library specifically does not delete the channel on Samsung devices.

The library has attempted to address these issues over time and using the fact that the router service uses a versioning system to pick which router service to start, it normally addresses the issues quickly as long as one app updates to the latest release.

#### Effective solution

With all that in mind, and mainly the notification system issues, we implemented the `SdlDeviceListner` as a way to determine SDL devices before the router service even starts. The drawback here, and specifically what these apps are seeing, is that older apps do not have this feature and they will simply start the newest router service. When the proposal was approved this was a clear downside and it was understood that we should really push all partners to update to the a version of the library that included this feature.


#### How can good app developers avoid the problems because of  developers who don't update.

There isn't a great solution here. I think we all understand that this is not ideal at all and it could turn some developers away from the platform. I don't believe that we as the library itself should handle this case, but I can suggest a potential code snippet. I have not tested this code but it should work if you want to test in your situations.

The following code could be put in one of two places I can think of offhand. 


##### Toggle SdlRouterService based on old implementations
```java
	private boolean handleOldSdlApps(Context context, ComponentName componentName) {
		final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
		boolean isFeatureSupported = SdlDeviceListener.isFeatureSupported(sdlAppInfoList);
		PackageManager packageManager = context.getPackageManager();
		if (packageManager != null) {
			int enabledState = isFeatureSupported ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED : PackageManager.COMPONENT_ENABLED_STATE_DISABLED;
			packageManager.setComponentEnabledSetting(componentName, enabledState, PackageManager.DONT_KILL_APP);
		}
		return isFeatureSupported;
	}
```

The first could go into the app's Application extension if they used a custom instance. 

###### CustomApplication extends Application 


```java
@Override
 public void onCreate() {
     super.onCreate();
     handleOldSdlApps(context, new ComponentName("enter router service package name here", "enter router service class name"));
     ...
}
```

Otherwise it could go into the SdlReceiver as such

###### SdlReceiver 
```java
	@Override
	public void onReceive(Context context, Intent intent) {

		if (handleOldSdlApps(context, new ComponentName("enter router service package name here", "enter router service class name"))) {
			super.onReceive(context, intent);
		} else {
			DebugTool.logWarning(TAG, "Old SDL apps installed");
		}
	}
```

**Comment by SilvioDC-Ford** [comment]
Thanks for this very detailled issue description and the code snippets, @joeygrover !

Unfortunately it did not solve the issue in either of the suggested positions.

When positioned in the router service, isFeatureSupported was always false when an App with old proxy was available and SDL connection was never established.

When positioning the snippet in the custom application, the app crashes upon connection to Sync with the sdl integration validator result:
    java.lang.RuntimeException: Unable to start receiver com.example.samplesdlapp.SdlReceiver: java.lang.RuntimeException: 

    -----------------------------------
      Integration Validator Results: 
    -----------------------------------
    ✓ Permission check passed
    
    ✕ This application has not specified its SdlRouterService correctly in the manifest.
    
    ✕ This application has not specified its intent-filter for the SdlRouterService.
    
    ✓ SdlBroadcastReceiver check passed


Any advice?

**Comment by joeygrover** [comment]
The router service definitely wasn't the right place, I thought possibly the SdlReceiver, but after some thought I crossed it out. The custom application is where it needed to go. So that exception is being thrown because it is checking the integration while in debug, and since the router service isn't enabled it doesn't see it as a valid integration. If you make a release build it should no longer cause the crash. 

However, it's possible to avoid this check in debug as well. Since this integration check happens in the SdlReceiver some additional code will need to be added there. Basically using similar code as previous examples but still doing the actual enable/disable in the custom application, the following code can be added to the SdlReceiver as well.

```java
@Override
public void onReceive(Context context, Intent intent) {
    final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
    if (sdlAppInfoList == null || sdlAppInfoList.isEmpty() || SdlDeviceListener.isFeatureSupported(sdlAppInfoList);) {
        super.onReceive(context, intent);
    } else {
        DebugTool.logWarning(TAG, "Old SDL apps installed");
    }
}
```

Please note the method I provided earlier `handleOldSdlApps` should also check if the list is null or empty and consider that a true value that the feature is supported.  Just realizing that if the router service is set to enabled=false, it will no longer appear in the list which can cause an issue. 

```java
	private boolean handleOldSdlApps(Context context, ComponentName componentName) {
		final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
		boolean isFeatureSupported = sdlAppInfoList == null || sdlAppInfoList.isEmpty() || SdlDeviceListener.isFeatureSupported(sdlAppInfoList);
		PackageManager packageManager = context.getPackageManager();
		if (packageManager != null) {
			int enabledState = isFeatureSupported ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED : PackageManager.COMPONENT_ENABLED_STATE_DISABLED;
			packageManager.setComponentEnabledSetting(componentName, enabledState, PackageManager.DONT_KILL_APP);
		}
		return isFeatureSupported;
	}

```

**Comment by SilvioDC-Ford** [comment]
Hi Joey,

sry the router service was a type, we tried your code in the SdlReceiver.

Thanks a lot for the extremely fast response. I added your snippets and the app now works on Sync and also does not crash if an app with an old library is installed on the phone. (I tested with Webex)
I could also trigger the temporary notification when connecting to my headphones and it disappeared as expected.
Thanks a lot!

**Comment by joeygrover** [comment]
Not a problem. I would advise doing a good amount of testing on that code before sending it to partners to be sure it works as expected, but glad to hear it initially seems to work!!

**Comment by SilvioDC-Ford** [comment]
Hi @joeygrover ,
while the initial tests looked promising I realised I got lucky with the router service determiniation and only got today time to actually follow the code and to try understanding it :)
Can you please comment on my assumptions:

We only get the full list of SDL apps in the sdlAppInfoList if we are the router app, otherwise the list consists only of the app which is calling?
If there is at least one app with an old RouterService in the sdlAppInfoList, the SdlRouterservice of the router app gets disabled and the app will never show up on the HMI?

Is there an easy way to add a check if the connected device is SDL enabled, so the apps are still showing on devices where they are expected to work? (To be honest, this check was what I expected in the method SdlDeviceListener.isFeatureSupported() )

Thanks a lot!

**Comment by joeygrover** [comment]
>We only get the full list of SDL apps in the sdlAppInfoList if we are the router app, otherwise the list consists only of the app which is calling?

No. The list should contain **all** SDL apps that have their `SdlRouterService` enabled. The application class gets initiated prior to any other code executing so there is no way to know who is hosting the router service yet, that should come after the bluetooth A2DP/Hands free profiles connect. You might be experiencing an issue based on a new requirement in Android SDK 30+ that affects the library. I actually just opened a PR to handle it better than the docs state #1652. You need to add a `queries` section to the app's manifest as seen in that PR.

>If there is at least one app with an old RouterService in the sdlAppInfoList, the SdlRouterservice of the router app gets disabled and the app will never show up on the HMI?

No. If there is an older router service present on the Android device, the code is intended to disable **only** the SdlRouterService component of the application in which has the sample code added to their custom application class. They should **not** be using this method with the component name of their `SdlService`, that would cause the app to not show up. However, when used as intended only the `SdlRouterService` will be disabled and the app will still be able to receive the connection intent from a different router service. This method is also not created to disable SDL for all applications; it is used to prevent a newer app from having their router service started in situations it should not be because older library integrations are present on the device. Those older applications should still start an acceptable and enabled `SdlRouterService`.

>Is there an easy way to add a check if the connected device is SDL enabled, so the apps are still showing on devices where they are expected to work? (To be honest, this check was what I expected in the method SdlDeviceListener.isFeatureSupported() )

If there was we wouldn't have issues with the notifications. ;) I believe my previous post explained some of that. The method I provided only checks to see if the device listener feature itself is supported, not SDL as a whole. The `SDLDeviceListener` feature is a preliminary connection that checks a device for SDL availability by making a successful bluetooth connection prior to attempting to start any `SDLRouterService`. Since older apps do not have this feature, they will not wait for this to occur (because they do not have the code) and start up the best router service available and enabled.

**Comment by SilvioDC-Ford** [comment]
Hi @joeygrover ,
The additional permissions helped and now I can always see in the Application already all other SDL apps! thanks :)

But the app still does not show on Sync if old apps are installed. 
Could this be because SdlDeviceListener.isFeatureSupported(sdlAppInfoList) in the SdlReceiver always returns false if old apps are in the list and "super.onReceive()" never gets called? 
Also, isn't the "queryForConnectedService()" method also affected by us disabling the SdlBroadcastReceiver?


Haha yes you are right, sorry the name sounded too nice ;)


Btw we now have also other partners with the same issue. Don't you think it would make sense to bring this fix in the library? It will most probably also effect app partners of other OEMs.

**Comment by joeygrover** [comment]
Just to check you added the `queries` tag and intent entries right? Not the permission? That specific permission is being moved to a sensitive permission from Google very soon so the `queries` tag is the correct addition.

Can you post the sample code of how you're using that method for a sanity check? I can dig deeper into this, but the only thing I can think of is there might be a usage of the router service entry for some other part of the logic flow that would prevent the older router service from sending the app that disabled their router service an intent to let it know an SDL device is connected. If that's the case, there's no way to change that logic in the apps that have the older router service so this might not work.

I think we should really push for apps to update rather than sponsor a band aid fix in the library itself. Obviously that comes with app developers needing to potentially add something like what we've been discussing, but we also need to be sure it works as expected first. Now we're seeing that it might not, so I will need some more time to dig in, but if you can provide your sample code that would be a good check as well.

**Comment by SilvioDC-Ford** [comment]
I tried it with both, the permission from the PR and the queries [as in the hello_sdl implementation](https://github.com/smartdevicelink/sdl_java_suite/pull/1652/commits/b2d6c3c8ad71a36e71fbb3a1526e0732ce24ab9f)
both with the same result.

In SdlReceiver:
    @Override
    public void onReceive(Context context, Intent intent) {
        //super.onReceive(context, intent);
        final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());

        if (sdlAppInfoList == null || sdlAppInfoList.isEmpty() || SdlDeviceListener.isFeatureSupported(sdlAppInfoList)) {
            super.onReceive(context, intent);
        } else {
            Log.d(TAG, "Old SDL apps installed"); //This is the last log I receive upon connection, if old apps are present;
        }
    }

If I delete the old apps, onSdlEnabled in the receiver gets called and the service starts normal.


Ok thanks for your feedback.

**Comment by joeygrover** [comment]
Yea Google is going to stop letting apps publish updates that use that permission without a good use case, so best to avoid it at all costs now.

Ok I see why this is working that way. I apologize for giving you this snippet without testing. That code snippet skips over the `onReceive` method if there's old router services installed. Meaning that yes, it will skip over the integration validation, but it will also skip past the code that triggers on the `onSDLEnabled` method and therefore the app won't show up on the IVI. Without some refactoring of the `SdlBroadcastReceiver` class the snippet is going to get a little messy. So for now I created an extension of the `SdlBroadcastReceiver` that should handle this. In the app's `SdlReceiver` impelementation extend this new class now instead of `SdlBroadcastReceiver`. It will act as a bridge to handle the messy code.



So first, create a new class with the name `SdlBroadcastReceiverBridge` and fill it in with the following:
```java

public abstract class SdlBroadcastReceiverBridge extends SdlBroadcastReceiver {
    private static final String TAG = "SdlBReceiverBridge";

    @Override
    public void onReceive(Context context, Intent intent) {
        final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
        final boolean isDeviceListenerSupported = SdlDeviceListener.isFeatureSupported(sdlAppInfoList);

        if (sdlAppInfoList == null || sdlAppInfoList.isEmpty() || isDeviceListenerSupported) {
            super.onReceive(context, intent);
        } else if (!isDeviceListenerSupported && TransportConstants.START_ROUTER_SERVICE_ACTION.equals(intent.getAction())) {
            //SDL is connected so we have to be sure to start our SDL service
            PackageManager packageManager = context.getPackageManager();
            Class routerService = defineLocalSdlRouterClass();
            if (packageManager != null && routerService != null) {
                ComponentName componentName = new ComponentName(context, routerService);
                if (componentName != null) {
                    if (packageManager.getComponentEnabledSetting(componentName) == PackageManager.COMPONENT_ENABLED_STATE_DISABLED) {
                        DebugTool.logInfo(TAG, "SdlRouterService is disabled, must be temporarily re-enabled to pass validation");
                        //In order to pass the validation step we need to make sure our router service is enabled
                        packageManager.setComponentEnabledSetting(componentName, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);
                        super.onReceive(context, intent);
                        packageManager.setComponentEnabledSetting(componentName, PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
                    } else {
                        super.onReceive(context, intent);
                    }

                }
            }
        } else {
            DebugTool.logInfo(TAG, "Old SDL apps installed"); //This is the last log I receive upon connection, if old apps are present;
        }
    }
}

```

Then, in the app's `SdlReceiver` class change 

```java
public class SdlReceiver extends SdlBroadcastReceiver
```

To

```java
public class SdlReceiver extends SdlBroadcastReceiverBridge
```

This is messier than I would like, but it's a tough situation to deal with. For now this bridge class should handle the desired outcome, but in the future the library could be refactored in a way that at least could better support this even if it doesn't include the code to do so directly. We are wrapping up a release so it will have to wait for a later release.

**Comment by SilvioDC-Ford** [comment]
Hi @joeygrover,

ok that's good to know. Great that we achieve the same with the queries :)

Thanks a lot for this ReceiverBridge :) I was unsure if we can temporally re-enable the RouterService but with this change it finally works fine in all testscenarios I have, related to this issue, and also root issue did not reappear ;)

I think that would be a good compromise for the future, to at least make the workaround simple :)

Thanks for your support on this issue!

**Comment by joeygrover** [comment]
Glad to hear it's working! I was focused on the `handleOldSdlApps` method and forgot I gave you that other snippet that caused some confusion. It's _ok_ to quickly re-enable the router service here, while theoretically it could mean that the app's specific router service is started somehow the probability is very small. Since the code checks to make sure that it only does this when it receives the specific intent for SDL connection it means that there is already a router service running and connected to the IVI. It's not ideal overall, but it should work without any modifications to the library itself.

If anything else comes up let me know and we can work through it.

**Comment by SilvioDC-Ford** [comment]
Hi @joeygrover ,

ok thanks for the clarification :)

it seems as if the quick disenable/reenable has some race condition when its not quick enough for the integration check.
If the phone is already connected to the HMI and the app is visible there, and then I manualy close the app on the phone, and reopen it, in around 4/10 cases it crashes when calling the Receiver with SdlReceiver.queryForConnectedService(this); in the MainActivities onCreate.
But as you said, when I build a release version, this crashes never occur to me.

**Comment by joeygrover** [comment]
Ahh ok, the code in the `Application` class and the new receiver class need to be synchronized. Easiest way to do that is to probably move the `handleOldSdlApps` code from the `Application` class into the receiver as a static method, then call it from the `Application` class. That way we can introduce a new object lock to make sure that the code is not executed at nearly the same time. So here's the updated receiver class, remove the `handleOldSdlApps` method from the application class and instead call the method from your app's extension of this bridge receiver class. (eg `SdlReceiver.handleOldSdlApps(context, componentName)` )

```java

public abstract class SdlBroadcastReceiverBridge extends SdlBroadcastReceiver {
    private static final String TAG = "SdlBReceiverBridge";
    private static final Object ROUTER_SERVICE_STATUS_LOCK = new Object();

    @Override
    public void onReceive(Context context, Intent intent) {
        final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
        final boolean isDeviceListenerSupported = SdlDeviceListener.isFeatureSupported(sdlAppInfoList);

        if (sdlAppInfoList == null || sdlAppInfoList.isEmpty() || isDeviceListenerSupported) {
            super.onReceive(context, intent);
        } else if (!isDeviceListenerSupported && TransportConstants.START_ROUTER_SERVICE_ACTION.equals(intent.getAction())) {
            synchronized (ROUTER_SERVICE_STATUS_LOCK) {
                //SDL is connected so we have to be sure to start our SDL service
                PackageManager packageManager = context.getPackageManager();
                Class routerService = defineLocalSdlRouterClass();
                if (packageManager != null && routerService != null) {
                    ComponentName componentName = new ComponentName(context, routerService);
                    if (componentName != null) {
                        if (packageManager.getComponentEnabledSetting(componentName) == PackageManager.COMPONENT_ENABLED_STATE_DISABLED) {
                            DebugTool.logInfo(TAG, "SdlRouterService is disabled, must be temporarily re-enabled to pass validation");
                            //In order to pass the validation step we need to make sure our router service is enabled
                            packageManager.setComponentEnabledSetting(componentName, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);
                            super.onReceive(context, intent);
                            packageManager.setComponentEnabledSetting(componentName, PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
                        } else {
                            super.onReceive(context, intent);
                        }
                    }
                }
            }
        } else {
            DebugTool.logInfo(TAG, "Old SDL apps installed"); //This is the last log I receive upon connection, if old apps are present;
        }
    }

    /**
     * This method will disable this app's SdlRouterService if there are old SDL apps that don't
     * support the new SdlDeviceListener feature. This prevents this application from having its
     * SdlRouterService started when it shouldn't be.
     *
     * @param context       an instance of this application's context
     * @param componentName the component name of this app's SdlRouterService
     * @return if the SdlDeviceListener feature is supported
     */
    public boolean handleOldSdlApps(Context context, ComponentName componentName) {
        final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
        boolean isFeatureSupported = sdlAppInfoList == null || sdlAppInfoList.isEmpty() || SdlDeviceListener.isFeatureSupported(sdlAppInfoList);
        PackageManager packageManager = context.getPackageManager();
        if (packageManager != null) {
            synchronized (ROUTER_SERVICE_STATUS_LOCK) {
                int enabledState = isFeatureSupported ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED : PackageManager.COMPONENT_ENABLED_STATE_DISABLED;
                packageManager.setComponentEnabledSetting(componentName, enabledState, PackageManager.DONT_KILL_APP);
            }
        }
        return isFeatureSupported;
    }

}

```

The only other situation we will have to be aware of is that since the `SdlRouterService` operates on a different process by design, it means a second Application instance is created when that router service process starts up. Since this still should prevent the router service from starting up that shouldn't be an issue, but it is something to keep watch of. static variables and states are unique to each process and can't be used for IPC.

**Comment by SilvioDC-Ford** [comment]
Thanks for the quick and detailed feedback :)
I will implement it on monday.
Have a great weekend!

**Comment by SilvioDC-Ford** [comment]
Hi @joeygrover,

unfortunately I still see the crashes happening when `SdlReceiver.queryForConnectedService(this)` is called in the MainActivities `onCreate`.
The crash only happens when I am already connected to Sync  and older sdl apps are also on the phone.
The crash is still triggered by the SDL Integration Validator.

Does it make sense to enable the routerservice before calling the `queryForConnectedService`?

**Comment by joeygrover** [comment]
Ah yea, that does make sense. It only shows up then because the library checks to see if the `localRouterClass` variable has been set or not while called from the `queryForConnectedService`. If it's null, a flag is set and the validator ignores the router service checks. However, when the `onReceive` method is called it will set that static variable, so if you are already connected then the variable is set and the validator does not ignore it. 

Sorry for the delay, releases this week and some high priority issues came up. I was also trying to think of a more clever way to not have the app partner's integration deviate more than it has. The best I can do is to have a new `compat` method the app calls from the `MainActivity` instead. I refactored some of the bridge class code as well to make it a bit cleaner and reduce redundant code for this new method. So copy and paste this into your `SdlBroadcastReceiverBridge` class:

```java
public abstract class SdlBroadcastReceiverBridge extends SdlBroadcastReceiver {
    private static final String TAG = "SdlBReceiverBridge";
    private static final Object ROUTER_SERVICE_STATUS_LOCK = new Object();

    @Override
    public void onReceive(final Context context, final Intent intent) {
        final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
        final boolean isDeviceListenerSupported = SdlDeviceListener.isFeatureSupported(sdlAppInfoList);

        if (sdlAppInfoList == null || sdlAppInfoList.isEmpty() || isDeviceListenerSupported) {
            super.onReceive(context, intent);
        } else if (!isDeviceListenerSupported && TransportConstants.START_ROUTER_SERVICE_ACTION.equals(intent.getAction())) {
            PackageManager packageManager = context.getPackageManager();
            Class routerService = defineLocalSdlRouterClass();
            if (packageManager != null && routerService != null) {
                ComponentName componentName = new ComponentName(context, routerService);
                handleTaskIfOldSDLApps(context, componentName, new CompletionListener() {
                    @Override
                    public void onComplete(boolean success) {
                        if (success) {
                            SdlBroadcastReceiverBridge.super.onReceive(context, intent);
                        }
                    }
                });
            }
        } else {
            DebugTool.logInfo(TAG, "Old SDL apps installed"); //This is the last log I receive upon connection, if old apps are present;
        }
    }

    /**
     * This method will check if there are old SDL apps installed and if the SdlRouterService implementation
     * of this app is disabled. If yes to both, this method will enable the SdlRouterService right
     * before calling completion listener to complete a task. 
     * @param context an instance of this app's context
     * @param routerService the component name of this app's SdlRouterService
     * @param completionListener a callback that performs the task that requires the SdlRouterService
     *                           to be enabled. It will pass true if the task should be performed,
     *                           and false if it should not.
     */
    private static void handleTaskIfOldSDLApps(Context context, ComponentName routerService, CompletionListener completionListener) {
        synchronized (ROUTER_SERVICE_STATUS_LOCK) {
            //SDL is connected so we have to be sure to start our SDL service
            PackageManager packageManager = context.getPackageManager();
            if (packageManager != null && routerService != null) {
                if (routerService != null) {
                    if (packageManager.getComponentEnabledSetting(routerService) == PackageManager.COMPONENT_ENABLED_STATE_DISABLED) {
                        DebugTool.logInfo(TAG, "SdlRouterService is disabled, must be temporarily re-enabled to pass validation");
                        //In order to pass the validation step we need to make sure our router service is enabled
                        packageManager.setComponentEnabledSetting(routerService, PackageManager.COMPONENT_ENABLED_STATE_ENABLED, PackageManager.DONT_KILL_APP);
                        if (completionListener != null) {
                            completionListener.onComplete(true);
                        }
                        packageManager.setComponentEnabledSetting(routerService, PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
                        return;
                    } else {
                        if (completionListener != null) {
                            completionListener.onComplete(true);
                        }
                        return;
                    }
                }
            }
        }
        if (completionListener != null) {
            completionListener.onComplete(false);
        }
    }

    /**
     * This method will disable this app's SdlRouterService if there are old SDL apps that don't
     * support the new SdlDeviceListener feature. This prevents this application from having its
     * SdlRouterService started when it shouldn't be.
     *
     * @param context       an instance of this application's context
     * @param componentName the component name of this app's SdlRouterService
     * @return if the SdlDeviceListener feature is supported
     */
    public static boolean handleOldSdlApps(Context context, ComponentName componentName) {
        final List<SdlAppInfo> sdlAppInfoList = AndroidTools.querySdlAppInfo(context, new SdlAppInfo.BestRouterComparator());
        boolean isFeatureSupported = sdlAppInfoList == null || sdlAppInfoList.isEmpty() || SdlDeviceListener.isFeatureSupported(sdlAppInfoList);
        PackageManager packageManager = context.getPackageManager();
        if (packageManager != null) {
            synchronized (ROUTER_SERVICE_STATUS_LOCK) {
                int enabledState = isFeatureSupported ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED : PackageManager.COMPONENT_ENABLED_STATE_DISABLED;
                packageManager.setComponentEnabledSetting(componentName, enabledState, PackageManager.DONT_KILL_APP);
            }
        }
        return isFeatureSupported;
    }

    /**
     * This method makes sure to handle the case where the router service is properly integrated, 
     * but is disabled because old SDL apps are installed.
     * @param context an instance of this app's context
     * @param routerService the component name of this app's SdlRouterService
     */
    public static void queryForConnectedServiceCompat(final Context context, ComponentName routerService) {
        Log.d(TAG, "In the hidden method");
        handleTaskIfOldSDLApps(context, routerService, new CompletionListener() {
            @Override
            public void onComplete(boolean success) {
                if (success) {
                    SdlBroadcastReceiver.queryForConnectedService(context);
                }
            }
        });
    }
}
```

Then in the `MainActivity` replace:

```java
SdlBroadcastReceiver.queryForConnectedService(context);
```

With:

```java
SdlBroadcastReceiverBridge.queryForConnectedServiceCompat(context, routerServiceComponentName);
```
You will have to get the `ComponentName` of the router service similar to how you do in the `Application` class for this method to work.

I also fixed the `handleOldSdlApps` which I forgot to make static so if you were creating an instance of the bridge class before calling it, you no longer need to do that and can just call it from the class itself.

I haven't had time to fully test this code, so please let me know if anything breaks and I will address ASAP.

**Comment by SilvioDC-Ford** [comment]
Hi @joeygrover,

thank you for the expansion of the workaround code!
Good news :)
I could not trigger any more crashes with this update, and also the initial issue with the notifications never reocurred during my testing :)

The only error I see when disconnecting from a TDK is a leaked IntentReceiver. Before the error, I see that unregistering was denied from the router service. I don't remember seeing this before so I assume it is related to this workaround. Do you see any potential issues arising from this?
This does not lead to a crash and the next connection with a new sdlManager works completely fine.

I/TransportManager: 5.0.0: Transport disconnected - Transport Type: BLUETOOTH Address: 04:A3:16:F4:1E:B6
I/SdlProtocol: 5.0.0: onTransportDisconnected - BLUETOOTH
I/SdlTransportBroker: 5.0.0: Stopping transport broker for com.sdl.android.126190245.10190019
I/SdlTransportBroker: 5.0.0: Attempting to unregister with Sdl Router Service
I/Lifecycle Manager: 5.0.0: onClose
I/BaseSubManager: 5.0.0: Proxy is closed.
D/SDL_Service: SDL service stopped
D/SDL_Service: SDL Service got destroyed
W/SdlTransportBroker: 5.0.0: Unregister request denied from router service. Reason - 1
D/SDL_Service: SDL Service got destroyed
E/ActivityThread: Service com.xxx.SdlService has leaked IntentReceiver com.smartdevicelink.util.MediaStreamingStatus$1@16c5732 that was originally registered here. Are you missing a call to unregisterReceiver()?

**Comment by joeygrover** [comment]
Hey @SilvioDC-Ford. great to hear!! Hopefully this is the one that works!

The error you posted isn't related to the code we've been adding. It seems there might be a bug that prevents that receiver from getting unregistered. It _shouldn't_ cause any issues, but something we should probably look into for a future bug fix.

**Comment by SilvioDC-Ford** [comment]
Hey @joeygrover,

ok thanks, I will search in my other code where this could result from and hope this notification topic is now closed :)
Thanks for all your help!
